# Generated by Django 5.2.11 on 2026-03-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("ra_position", "Research Assistant Position"),
                            ("phd_opening", "PhD Opening"),
                            ("masters_opening", "Masters Opening"),
                            ("postdoc", "Postdoc Position"),
                            ("collaboration", "Collaboration Request"),
                            ("project", "Project Announcement"),
                            ("internship", "Research Internship"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("professor", "Professor"),
                            ("phd_student", "PhD Student"),
                            ("masters_student", "Masters Student"),
                            ("undergraduate", "Undergraduate"),
                            ("independent_researcher", "Independent Researcher"),
                        ],
                        default="any",
                        max_length=30,
                    ),
                ),
                ("funding_available", models.BooleanField(default=False)),
                ("stipend_details", models.CharField(blank=True, max_length=255)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("external_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
