# Generated by Django 5.2.11 on 2026-03-01 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="research_areas",
            field=models.ManyToManyField(
                blank=True, related_name="opportunities", to="users.researchinterest"
            ),
        ),
        migrations.AddField(
            model_name="opportunitybookmark",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarked_by",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunitybookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["opportunity_type", "is_active"],
                name="opportuniti_opportu_edc635_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["author", "created_at"], name="opportuniti_author__5e31e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="opportunitybookmark",
            unique_together={("user", "opportunity")},
        ),
    ]
